# -*- coding: utf-8 -*-
"""app_v1p4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SxlEaz1oE959A4BzgUfCG9FRJaZXq3R
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import savgol_filter
from scipy.sparse import csc_matrix, spdiags
from scipy.sparse.linalg import factorized
import io
import requests

# Set page configuration
st.set_page_config(layout="wide", page_title="Vibrational Spectroscopy Preprocess")

# --- Helper Functions (unchanged from original logic) ---
def baseline_als(y, lam, p, niter=10):
    L = len(y)
    D = csc_matrix(np.diff(np.eye(L), 2))
    w = np.ones(L)
    for _ in range(niter):
        W = spdiags(w, 0, L, L)
        Z = W + lam * D.dot(D.transpose())
        C = factorized(Z)
        z = C(W.dot(y))
        w = p * (y > z) + (1 - p) * (y < z)
    return z

def rubberband_correction(y, x):
    baseline_points_indices = np.argmin(y, axis=0)
    baseline_points_x = x[baseline_points_indices]
    baseline_points_y = y[baseline_points_indices]
    if len(baseline_points_indices) > 1:
        baseline_fit = np.polyfit(baseline_points_x, baseline_points_y, 1)
        baseline = np.polyval(baseline_fit, x)
    else:
        baseline = np.full_like(x, baseline_points_y[0])
    return y - baseline

def linear_baseline_correction(y):
    return y - y[0] - (y[-1] - y[0]) * (np.arange(len(y)) / (len(y) - 1))

# --- Session State Initialization ---
if 'wavenumbers' not in st.session_state:
    st.session_state.wavenumbers = None
if 'spectra_data' not in st.session_state:
    st.session_state.spectra_data = None
if 'history' not in st.session_state:
    st.session_state.history = []
if 'current_index' not in st.session_state:
    st.session_state.current_index = 0
if 'selected_spectroscopy_type' not in st.session_state:
    st.session_state.selected_spectroscopy_type = "FTIR" # Default value

# --- Streamlit-aware Functions ---
def load_and_initialize_data_st(uploaded_file):
    try:
        file_content = uploaded_file.getvalue()
        s = io.StringIO(file_content.decode('utf-8'))

        # Load the data skipping the first row (wavenumbers in the first row)
        df_raw = pd.read_csv(s, sep=",", header=None, skiprows=[0])
        s.seek(0) # Reset stream position to read again for wavenumbers
        # Read the wavenumbers from the first row separately
        wavenumbers_df_raw = pd.read_csv(s, sep=",", nrows=1, header=None)
        wavenumbers = wavenumbers_df_raw.values[0].astype(float)
        spectra_data = df_raw.values

        # Reset processing state in session_state
        st.session_state.wavenumbers = wavenumbers
        st.session_state.spectra_data = spectra_data
        st.session_state.history = [{
            "wavenumbers": wavenumbers,
            "spectra": spectra_data,
            "label": "Original"
        }]
        st.session_state.current_index = 0
        st.session_state.selected_spectroscopy_type = "FTIR" # Reset to default
        st.success(f"File '{uploaded_file.name}' loaded successfully.")
        return True
    except Exception as e:
        st.error(f"Error loading '{uploaded_file.name}': {str(e)}")
        return False

def plot_spectra_st(wavenumbers_param, spectra_param, title="", current_spectroscopy_type="FTIR"):
    if wavenumbers_param is None or spectra_param is None or len(wavenumbers_param) == 0:
        st.write("Nenhum dado para plotar.")
        return None

    fig, ax = plt.subplots(figsize=(8,5))
    for i in range(spectra_param.shape[0]):
        ax.plot(wavenumbers_param, spectra_param[i, :])

    ax.set_xlabel("Wavenumber (cm⁻¹)")
    if current_spectroscopy_type == "Raman":
        ax.set_ylabel("Raman intensity)")
    else: # Default to FTIR
        ax.set_ylabel("Absorbance (a.u.)")
        ax.invert_xaxis()

    ax.set_title(title)
    ax.grid(True)
    plt.tight_layout()
    return fig

def update_plot_st():
    if st.session_state.history and st.session_state.current_index < len(st.session_state.history) and st.session_state.history[st.session_state.current_index]["wavenumbers"] is not None:
        fig = plot_spectra_st(st.session_state.history[st.session_state.current_index]["wavenumbers"],
                              st.session_state.history[st.session_state.current_index]["spectra"],
                              title=st.session_state.history[st.session_state.current_index]["label"],
                              current_spectroscopy_type=st.session_state.selected_spectroscopy_type)
        if fig:
            st.pyplot(fig)
            plt.close(fig) # Close the figure to prevent display issues
    else:
        st.write("No data to plot. Please upload a file.")

def add_history_st(wn, sp, label):
    st.session_state.history.append({"wavenumbers": wn, "spectra": sp, "label": label})
    st.session_state.current_index = len(st.session_state.history) - 1

def go_back_st():
    if st.session_state.current_index > 0:
        st.session_state.current_index -= 1
        st.rerun() # Rerun to update the plot
    else:
        st.warning("It's back to its original state. It's not possible to revert back.")

def on_refresh_button_clicked_st():
    # Reset all session state variables
    for key in list(st.session_state.keys()):
        del st.session_state[key]
    st.success("Application reset. Please upload a new file.")
    st.rerun() # Rerun the app from scratch

# --- Apply Operation Functions (use session_state data, return new data) ---
def apply_cut(start_wave, end_wave):
    if not st.session_state.history or st.session_state.history[st.session_state.current_index]["wavenumbers"] is None:
        st.error("Erro: No data loaded to apply the cutting operation.")
        return None, None
    wn, sp = st.session_state.history[st.session_state.current_index]["wavenumbers"], st.session_state.history[st.session_state.current_index]["spectra"]

    min_val = min(start_wave, end_wave)
    max_val = max(start_wave, end_wave)

    cut_indices = np.where((wn >= min_val) & (wn <= max_val))[0]
    if len(cut_indices) == 0:
        st.warning(f"Warning: No spectral band found between {start_wave} and {end_wave}. No changes applied.")
        return wn, sp # Return original if no cut
    return wn[cut_indices], sp[:, cut_indices]

def apply_remove_band(start_wave, end_wave):
    if not st.session_state.history or st.session_state.history[st.session_state.current_index]["wavenumbers"] is None:
        st.error("Erro: No data loaded to apply the band removal operation.")
        return None, None
    wn, sp = st.session_state.history[st.session_state.current_index]["wavenumbers"], st.session_state.history[st.session_state.current_index]["spectra"]

    min_val = min(start_wave, end_wave)
    max_val = max(start_wave, end_wave)

    # Select indices OUTSIDE the specified range
    keep_indices = np.where((wn < min_val) | (wn > max_val))[0]

    if len(keep_indices) == 0:
        st.warning(f"Warning: Removing the band {start_wave}-{end_wave} would result in no data. No changes applied.")
        return wn, sp
    return wn[keep_indices], sp[:, keep_indices]

def apply_smoothing(polyorder, window_length, derivative):
    if not st.session_state.history or st.session_state.history[st.session_state.current_index]["wavenumbers"] is None:
        st.error("Error: No data loaded to apply smoothing.")
        return None, None
    wn, sp = st.session_state.history[st.session_state.current_index]["wavenumbers"], st.session_state.history[st.session_state.current_index]["spectra"]
    try:
        # Ensure window_length is odd and greater than polyorder
        if window_length % 2 == 0:
            st.error("Window length must be an odd number.")
            return wn, sp
        if window_length <= polyorder:
            st.error("Window length must be greater than polynomial order.")
            return wn, sp

        smoothed = savgol_filter(sp, window_length=window_length, polyorder=polyorder, deriv=derivative, axis=1)
        return wn, smoothed
    except ValueError as e:
        st.error(f"Error in smoothing: {e}. Check parameters.")
        return wn, sp # Return original if error

def apply_baseline(option, lam=100, p=0.01, niter=10):
    if not st.session_state.history or st.session_state.history[st.session_state.current_index]["wavenumbers"] is None:
        st.error("Error: No data loaded to apply baseline correction.")
        return None, None
    wn, sp = st.session_state.history[st.session_state.current_index]["wavenumbers"], st.session_state.history[st.session_state.current_index]["spectra"]
    corrected = np.copy(sp)
    # Removed Rubber Band (A) as per Streamlit adaptation requirements
    if option == "B": # Linear
        for i in range(sp.shape[0]):
            corrected[i, :] = linear_baseline_correction(sp[i, :])
    elif option == "C": # ALS
        for i in range(sp.shape[0]):
            corrected[i, :] = sp[i, :] - baseline_als(sp[i, :], lam, p, niter)
    return wn, corrected

def apply_normalization(option, target_range="0-1"):
    if not st.session_state.history or st.session_state.history[st.session_state.current_index]["wavenumbers"] is None:
        st.error("Error: No data loaded to apply normalization.")
        return None, None
    wn, sp = st.session_state.history[st.session_state.current_index]["wavenumbers"], st.session_state.history[st.session_state.current_index]["spectra"]
    normed = np.copy(sp)
    if option == "A": # Min-Max normalization
        min_vals = np.min(sp, axis=1, keepdims=True)
        max_vals = np.max(sp, axis=1, keepdims=True)
        if np.any(max_vals - min_vals == 0):
            st.warning("Warning: Min-Max normalization attempt on spectra with zero range. Returning original data.")
            return wn, sp
        normed = (sp - min_vals) / (max_vals - min_vals)
        if target_range == "0-100":
            normed = normed * 100
    elif option == "B": # SNV
        mean_vals = np.mean(sp, axis=1, keepdims=True)
        std_vals = np.std(sp, axis=1, keepdims=True)
        if np.any(std_vals == 0):
            st.warning("Warning: Attempting SNV normalization on spectra with zero standard deviation. Returning original data.")
            return wn, sp
        normed = (sp - mean_vals) / std_vals
    return wn, normed

def apply_offset(value, axis='y'):
    if not st.session_state.history or st.session_state.history[st.session_state.current_index]["wavenumbers"] is None:
        st.error("Error: No data loaded to apply the offset.")
        return None, None
    current_wn = np.copy(st.session_state.history[st.session_state.current_index]["wavenumbers"])
    current_sp = np.copy(st.session_state.history[st.session_state.current_index]["spectra"])

    if axis == 'y':
        current_sp += value
    elif axis == 'x':
        current_wn += value
    else:
        st.error("Axis must be 'x' or 'y'.")
        return current_wn, current_sp

    return current_wn, current_sp

def apply_cosmic_ray_removal(window_length, threshold_factor=3):
    if not st.session_state.history or st.session_state.history[st.session_state.current_index]["wavenumbers"] is None:
        st.error("Error: No data loaded to apply cosmic ray removal.")
        return None, None
    wn, sp = st.session_state.history[st.session_state.current_index]["wavenumbers"], st.session_state.history[st.session_state.current_index]["spectra"]
    corrected_sp = np.copy(sp)

    # Ensure window_length is odd and at least 3 for savgol_filter
    if window_length % 2 == 0:
        st.warning("Window length for cosmic ray removal must be an odd number. Adjusting to nearest odd.")
        window_length = window_length + 1 if window_length % 2 == 0 else window_length
    if window_length < 3:
        st.warning("Window length for cosmic ray removal must be at least 3. Adjusting to 3.")
        window_length = 3

    for i in range(sp.shape[0]):
        spectrum = sp[i, :]

        # Apply Savitzky-Golay filter to get a smoothed baseline for residual calculation
        # polyorder must be less than window_length
        polyorder = min(window_length - 1, 2) # Use 2nd order polynomial, or max possible if window_length is small
        try:
            smoothed_spectrum = savgol_filter(spectrum, window_length=window_length, polyorder=polyorder, deriv=0, mode='nearest')
        except ValueError as e:
            st.error(f"Error applying Savitzky-Golay filter for cosmic ray detection in spectrum {i}: {e}. Check window length and polyorder.")
            return wn, sp # Return original if error

        # Calculate residuals
        residuals = spectrum - smoothed_spectrum

        # Identify outliers (cosmic rays) using a robust statistic (MAD)
        mad = np.median(np.abs(residuals - np.median(residuals)))

        # If MAD is very small or zero, use a small epsilon or skip
        if mad < 1e-9:
            std_residuals = np.std(residuals)
            if std_residuals < 1e-9: # Effectively zero std dev, no variance, no outliers to remove
                continue
        else:
            std_residuals = mad * 1.4826 # Conversion from MAD to std for normal distribution

        outlier_indices = np.where(np.abs(residuals) > threshold_factor * std_residuals)[0]

        # Interpolate the outliers
        if len(outlier_indices) > 0:
            temp_spectrum = np.copy(spectrum)
            temp_spectrum[outlier_indices] = np.nan # Mark outliers with NaN for interpolation

            # Find non-NaN indices
            not_nan_indices = np.where(~np.isnan(temp_spectrum))[0]

            if len(not_nan_indices) > 1: # Need at least two points to interpolate
                # Linear interpolation
                corrected_sp[i, outlier_indices] = np.interp(outlier_indices, not_nan_indices, temp_spectrum[not_nan_indices])
            elif len(not_nan_indices) == 1: # If only one non-NaN, fill with that value
                 corrected_sp[i, outlier_indices] = temp_spectrum[not_nan_indices[0]]
            # If len(not_nan_indices) is 0, all values are NaN, cannot interpolate, keep original at outlier_indices

    return wn, corrected_sp

# --- Streamlit UI ---

st.markdown("<h1 style='text-align: center;'>Vibrational Spectroscopy Preprocess</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center;'>v. 1.4, 2026.</p>", unsafe_allow_html=True)

# Header image (fetching from Google Drive URL)
google_drive_file_id = "1l0DJmPOvyaAitRs7xdIdJHremEtHud0r"
direct_download_url = f"https://drive.google.com/uc?export=download&id={google_drive_file_id}"

try:
    response = requests.get(direct_download_url)
    response.raise_for_status()
    st.image(response.content, width=315)
except requests.exceptions.RequestException as e:
    st.warning(f"Erro ao carregar a imagem do Google Drive: {e}. Exibindo placeholder.")
    st.markdown("<p style='text-align:center;'><b>Vibrational Spectroscopy Preprocess</b></p>", unsafe_allow_html=True)

st.markdown("""
<p><b>This software was developed for the spectral preprocess of Raman and FTIR spectroscopy data.</b></p>
<p><b>DATA FORMAT REQUIRED</b></p>
<ul>
    <li>The input file must be in .csv format.</li>
    <li>Each row should represent an individual spectrum.</li>
    <li>The first row must contain the wavenumber values.</li>
    <li>Spectra only, without labels/categories.</li>
</ul>
<p>Make sure your file follows this format to ensure proper functioning of the script.</p>
<p><b>LICENSE</b></p>
<p>This app is licensed under the CC BY-NC-ND 4.0 License.</p>
<p>You are allowed to use and share this application for non-commercial purposes, provided that proper credit is given to the author.</p>
<p>If any data, results, or content generated by this application are published or shared, appropriate attribution must be clearly provided.</p>
<p>Modification, redistribution of modified versions, or commercial use of this application or its contents is not permitted without prior written permission from the author.</p>
<p><b>RESEARCH BACKGROUND</b></p>
<p>This code is part of a Ph.D. research project conducted at the Laboratory of Biophotonics, at Nuclear and Energy Research Institute (IPEN-CNEN), University of São Paulo, focusing on the use of spectroscopic and computational tools for the characterization of biological samples.</p>
<p>PhD Student - Vinicius Pereira dos Anjos, PhD Advisor - Prof. Dr. Denise Maria Zezell.
</p>
<p>Learn more about the lab: <a href=\"https://biophotonics.my.canva.site/\" target=\"_blank\">https://biophotonics.my.canva.site/</a></p>
""", unsafe_allow_html=True)

uploaded_file = st.file_uploader("Upload your CSV file", type="csv", key="file_uploader")

# Main application logic
if uploaded_file is not None and (st.session_state.wavenumbers is None or st.session_state.spectra_data is None):
    # Only load and initialize if a new file is uploaded or state is empty
    load_and_initialize_data_st(uploaded_file)


if st.session_state.wavenumbers is not None and st.session_state.spectra_data is not None:
    # Display the main application UI after data is loaded
    st.sidebar.header("Operations")

    # Spectroscopy choice
    st.session_state.selected_spectroscopy_type = st.sidebar.radio(
        "Spectroscopy Type:",
        options=['FTIR', 'Raman'],
        index=0 if st.session_state.selected_spectroscopy_type == "FTIR" else 1,
        key="spectroscopy_radio"
    )

    # Operation menu
    operation_choice = st.sidebar.selectbox(
        "Select an operation:",
        options=[
            "Select an operation",
            "Spectral cut",
            "Remove band", # Added remove band
            "Smoothing (Savitzky-Golay)",
            "Baseline correction",
            "Normalization",
            "Offset",
            "Cosmic Ray Removal" # Added Cosmic Ray Removal
        ],
        key="operation_select"
    )

    # Parameters for operations
    if operation_choice == "Spectral cut":
        with st.sidebar.expander("Spectral Cut Parameters"): # Using expander for cleaner UI
            start_wave = st.number_input("Low limit (cm⁻¹):", value=4000.0, key="cut_start")
            end_wave = st.number_input("High limit (cm⁻¹):", value=400.0, key="cut_end")
            if st.button("Apply cut", key="apply_cut_btn"):
                wn, sp = apply_cut(start_wave, end_wave)
                if wn is not None and sp is not None:
                    add_history_st(wn, sp, f"Cut {start_wave}-{end_wave}")
                    st.rerun()

    elif operation_choice == "Remove band":
        with st.sidebar.expander("Remove Band Parameters"): # Using expander for cleaner UI
            start_wave = st.number_input("Band start (cm⁻¹):", value=2800.0, key="remove_band_start")
            end_wave = st.number_input("Band end (cm⁻¹):", value=3000.0, key="remove_band_end")
            if st.button("Remove band", key="apply_remove_band_btn"):
                wn, sp = apply_remove_band(start_wave, end_wave)
                if wn is not None and sp is not None:
                    add_history_st(wn, sp, f"Remove band {start_wave}-{end_wave}")
                    st.rerun()

    elif operation_choice == "Smoothing (Savitzky-Golay)":
        with st.sidebar.expander("Smoothing Parameters"): # Using expander for cleaner UI
            poly = st.number_input("Polynomial order:", value=3, min_value=0, key="smooth_poly")
            window = st.number_input("Window (Odd):", value=7, min_value=1, step=2, key="smooth_window")
            deriv = st.number_input("Derivative:", value=0, min_value=0, key="smooth_deriv")
            if st.button("Apply smoothing", key="apply_smooth_btn"):
                wn, sp = apply_smoothing(poly, window, deriv)
                if wn is not None and sp is not None:
                    add_history_st(wn, sp, f"Smooth SG (poly={poly}, win={window})")
                    st.rerun()

    elif operation_choice == "Baseline correction":
        with st.sidebar.expander("Baseline Correction Parameters"): # Using expander for cleaner UI
            # Removed Rubber Band (A) from Streamlit adaptation
            baseline_method_options = [("Linear", "B"), ("ALS", "C")]
            baseline_method_tuple = st.selectbox(
                "Method:",
                options=baseline_method_options,
                format_func=lambda x: x[0],
                key="baseline_method"
            )
            baseline_method_value = baseline_method_tuple[1]

            lam, p, niter_input = 100.0, 0.01, 10 # Default values

            if baseline_method_value == "C": # ALS parameters
                lam = st.number_input("Lambda (ALS):", value=100.0, key="baseline_lam")
                p = st.number_input("p (ALS):", value=0.01, key="baseline_p")
                niter_input = st.number_input("Niter (ALS):", value=10, key="baseline_niter")

            if st.button("Apply baseline", key="apply_baseline_btn"):
                wn, sp = apply_baseline(baseline_method_value, lam, p, niter_input)
                if wn is not None and sp is not None:
                    add_history_st(wn, sp, f"Baseline {baseline_method_tuple[0]}")
                    st.rerun()

    elif operation_choice == "Normalization":
        with st.sidebar.expander("Normalization Parameters"): # Using expander for cleaner UI
            norm_method_options = [("Min-Max", "A"), ("SNV", "B")]
            norm_method_tuple = st.selectbox(
                "Method:",
                options=norm_method_options,
                format_func=lambda x: x[0],
                key="norm_method"
            )
            norm_method_value = norm_method_tuple[1]

            target_range = "0-1"
            if norm_method_value == "A":
                target_range = st.radio(
                    "Target Range:",
                    options=['0-1', '0-100'],
                    index=0,
                    key="norm_range"
                )
            if st.button("Apply normalization", key="apply_norm_btn"):
                wn, sp = apply_normalization(norm_method_value, target_range)
                if wn is not None and sp is not None:
                    label = f"Normalization {norm_method_tuple[0]}"
                    if norm_method_value == 'A':
                        label += f" ({target_range})"
                    add_history_st(wn, sp, label)
                    st.rerun()

    elif operation_choice == "Offset":
        with st.sidebar.expander("Offset Parameters"): # Using expander for cleaner UI
            y_offset_step = st.number_input("Y-Step:", value=0.1, key="offset_y_step")
            x_offset_step = st.number_input("X-Step:", value=1.0, key="offset_x_step")

            col1_btn, col2_btn = st.columns(2)
            with col1_btn:
                if st.button("⬆️ (Y-axis)", key="offset_y_up"):
                    wn, sp = apply_offset(y_offset_step, axis='y')
                    if wn is not None and sp is not None:
                        add_history_st(wn, sp, f"Offset Y +{y_offset_step:+.2f}")
                        st.rerun()
                if st.button("⬇️ (Y-axis)", key="offset_y_down"):
                    wn, sp = apply_offset(-y_offset_step, axis='y')
                    if wn is not None and sp is not None:
                        add_history_st(wn, sp, f"Offset Y -{y_offset_step:+.2f}")
                        st.rerun()
            with col2_btn:
                if st.button("⬅️ (X-axis)", key="offset_x_left"):
                    wn, sp = apply_offset(-x_offset_step, axis='x')
                    if wn is not None and sp is not None:
                        add_history_st(wn, sp, f"Offset X -{x_offset_step:+.2f}")
                        st.rerun()
                if st.button("➡️ (X-axis)", key="offset_x_right"):
                    wn, sp = apply_offset(x_offset_step, axis='x')
                    if wn is not None and sp is not None:
                        add_history_st(wn, sp, f"Offset X +{x_offset_step:+.2f}")
                        st.rerun()

    elif operation_choice == "Cosmic Ray Removal":
        with st.sidebar.expander("Cosmic Ray Removal Parameters"): # Using expander for cleaner UI
            window_length_input = st.number_input("Window Length (Odd, >=3):", value=5, min_value=3, step=2, key="cr_window_length")
            threshold_input = st.number_input("Threshold Factor (e.g., 3):", value=3.0, min_value=0.1, key="cr_threshold")
            if st.button("Apply Cosmic Ray Removal", key="apply_cr_btn"):
                wn, sp_corrected = apply_cosmic_ray_removal(window_length_input, threshold_input)
                if wn is not None and sp_corrected is not None:
                    add_history_st(wn, sp_corrected, f"Cosmic Ray Removal (win={window_length_input}, thres={threshold_input})")
                    st.rerun()

    st.sidebar.markdown("---")

    col_back, col_save, col_refresh = st.sidebar.columns(3)
    with col_back:
        if st.button("⏪ Back operation", key="back_btn"):
            go_back_st()
    with col_save:
        if st.session_state.history and st.session_state.current_index < len(st.session_state.history) and st.session_state.history[st.session_state.current_index]["wavenumbers"] is not None:
            # Get current wavenumbers and spectra
            current_wn = st.session_state.history[st.session_state.current_index]["wavenumbers"]
            current_sp = st.session_state.history[st.session_state.current_index]["spectra"]

            # Create a DataFrame with wavenumbers as the first row and spectra data following
            # Convert wavenumbers to a list of lists for a single row DataFrame
            wavenumber_row_df = pd.DataFrame([current_wn])
            # Convert spectra to a DataFrame
            spectra_df = pd.DataFrame(current_sp)
            # Concatenate them vertically
            combined_df = pd.concat([wavenumber_row_df, spectra_df], ignore_index=True)

            # Save to CSV without a header (as the first row of data is now the wavenumbers)
            output_df_content = combined_df.to_csv(index=False, header=False).encode('utf-8')

            st.download_button(
                label="💾 Save result",
                data=output_df_content,
                file_name="preprocess.csv",
                mime="text/csv",
                key="download_btn"
            )
        else:
            st.button("💾 Save result", disabled=True, key="download_disabled_btn")
    with col_refresh:
        if st.button("🔄 Refresh", key="refresh_btn"):
            on_refresh_button_clicked_st()

    st.markdown("---<br>", unsafe_allow_html=True)
    # Main content area for the plot
    st.subheader(f"Current State: {st.session_state.history[st.session_state.current_index]['label']}")
    update_plot_st()
else:
    if uploaded_file is None and 'history' in st.session_state and len(st.session_state.history) > 0:
        st.warning("Data is loaded, but file uploader state might have reset. Please use the sidebar controls or re-upload if needed.")
    elif uploaded_file is None:
        st.info("Please upload a CSV file to begin spectroscopy data preprocessing.")